application:    i-fromz
version:        102
runtime:        php55
api_version:    1
threadsafe: true

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        #- url: /build
        # static_dir: public/build
        # application_readable: true

        - url: /.*
          script: public/index.php


env_variables:
        APP_DEBUG: '1'
        APP_KEY: 'AppServerForiinbandBypkfromz2015'
        APP_CIPHER: 'rijndael-128'

        DB_HOST: '188.166.245.4'
        DB_USERNAME: 'pkfrom'
        DB_PASSWORD: 'faster'
        DB_DATABASE: 'app-engine'

        CACHE_DRIVER: 'memcached'
        SESSION_DRIVER: 'memcached'
        MAIL_DRIVER: 'mail'
        APP_LOG: 'syslog'
        STORAGE_PATH: 'gs://i-fromz.appspot.com/i-fromz/storage'
       # GAE_SKIP_GCS_INIT: false